OBJECT.CONST = {
    "KxpaxUSuBC7hr4F7": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/KxpaxUSuBC7hr4F7",
        "id"          : "KxpaxUSuBC7hr4F7",
        "price"       : null,
        "required"    : [],
        "text"        : "Aboutissement exemplaire",
        "traits"      : []
    },
    "LbPLNWlLCxKCo5gF": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/LbPLNWlLCxKCo5gF",
        "id"          : "LbPLNWlLCxKCo5gF",
        "price"       : null,
        "required"    : [],
        "text"        : "Accès au savoir",
        "traits"      : []
    },
    "tlSE7Ly8vi1Dgddv": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/tlSE7Ly8vi1Dgddv",
        "id"          : "tlSE7Ly8vi1Dgddv",
        "price"       : null,
        "required"    : [],
        "text"        : "Accès de rigolade",
        "traits"      : []
    },
    "pHrVvoTKygXeczVG": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "item",
        "description" : "",
        "element_type": null,
        "href"        : "/equipment/pHrVvoTKygXeczVG",
        "id"          : "pHrVvoTKygXeczVG",
        "price"       : null,
        "required"    : [],
        "text"        : "Amulette de la nymphe",
        "traits"      : []
    },
    "KR8WgdazifDBjDkW": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/KR8WgdazifDBjDkW",
        "id"          : "KR8WgdazifDBjDkW",
        "price"       : null,
        "required"    : [],
        "text"        : "Aubaine inattendue",
        "traits"      : []
    },
    "enQieRrITuEQZxx2": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/enQieRrITuEQZxx2",
        "id"          : "enQieRrITuEQZxx2",
        "price"       : null,
        "required"    : [],
        "text"        : "Bouclier égoïste",
        "traits"      : []
    },
    "pIHjH1x0AVtiX5Tv": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/pIHjH1x0AVtiX5Tv",
        "id"          : "pIHjH1x0AVtiX5Tv",
        "price"       : null,
        "required"    : [],
        "text"        : "C'est étrange",
        "traits"      : []
    },
    "Nun72GTmb31YqSKh": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "item",
        "description" : "",
        "element_type": null,
        "href"        : "/equipment/Nun72GTmb31YqSKh",
        "id"          : "Nun72GTmb31YqSKh",
        "price"       : null,
        "required"    : [],
        "text"        : "Cape d'invisibilité",
        "traits"      : []
    },
    "AlbpWWN87yGegoAF": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/AlbpWWN87yGegoAF",
        "id"          : "AlbpWWN87yGegoAF",
        "price"       : null,
        "required"    : [],
        "text"        : "Cible verrouillée",
        "traits"      : []
    },
    "jSkJIWPfSZZzvYzq": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/jSkJIWPfSZZzvYzq",
        "id"          : "jSkJIWPfSZZzvYzq",
        "price"       : null,
        "required"    : [],
        "text"        : "Combiner des élixirs",
        "traits"      : []
    },
    "VjQfJKeDc46cWtgk": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/VjQfJKeDc46cWtgk",
        "id"          : "VjQfJKeDc46cWtgk",
        "price"       : null,
        "required"    : [],
        "text"        : "Communication zoophonique",
        "traits"      : []
    },
    "f2Pl5dWEL9ZvEyI1": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/f2Pl5dWEL9ZvEyI1",
        "id"          : "f2Pl5dWEL9ZvEyI1",
        "price"       : null,
        "required"    : [],
        "text"        : "Compagnon animal",
        "traits"      : []
    },
    "sVjATEo8eqkAosNp": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/sVjATEo8eqkAosNp",
        "id"          : "sVjATEo8eqkAosNp",
        "price"       : null,
        "required"    : [],
        "text"        : "Composition prolongée",
        "traits"      : []
    },
    "G0T1xv1FoZ23Jxvt": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/G0T1xv1FoZ23Jxvt",
        "id"          : "G0T1xv1FoZ23Jxvt",
        "price"       : null,
        "required"    : [],
        "text"        : "Coup de pouce du destin",
        "traits"      : []
    },
    "YKexU7BkwNq4ESCc": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "condition",
        "description" : "",
        "element_type": null,
        "href"        : "/conditions/YKexU7BkwNq4ESCc",
        "id"          : "YKexU7BkwNq4ESCc",
        "price"       : null,
        "required"    : [],
        "text"        : "Dentelé",
        "traits"      : []
    },
    "qVNVSmsgpKFGk9hV": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/qVNVSmsgpKFGk9hV",
        "id"          : "qVNVSmsgpKFGk9hV",
        "price"       : null,
        "required"    : [],
        "text"        : "Dissimulé cet objet",
        "traits"      : []
    },
    "rmnhzmJqfzEVnz1h": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/rmnhzmJqfzEVnz1h",
        "id"          : "rmnhzmJqfzEVnz1h",
        "price"       : null,
        "required"    : [],
        "text"        : "Drain de familier",
        "traits"      : []
    },
    "aqnx6IDcB7ARLxS5": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "effect",
        "description" : "",
        "element_type": null,
        "href"        : "/effects/aqnx6IDcB7ARLxS5",
        "id"          : "aqnx6IDcB7ARLxS5",
        "price"       : null,
        "required"    : [],
        "text"        : "Effet : Magie du sang Béni du ver (pénalité de statut - cible)",
        "traits"      : []
    },
    "ruRAfGJnik7lRavk": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "effect",
        "description" : "",
        "element_type": null,
        "href"        : "/effects/ruRAfGJnik7lRavk",
        "id"          : "ruRAfGJnik7lRavk",
        "price"       : null,
        "required"    : [],
        "text"        : "Effet : Magie du sang nymphe (cible) (Soi)",
        "traits"      : []
    },
    "UpEjRfQkCJCruAfb": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/UpEjRfQkCJCruAfb",
        "id"          : "UpEjRfQkCJCruAfb",
        "price"       : null,
        "required"    : [],
        "text"        : "Enfant de la tempête",
        "traits"      : []
    },
    "LyqqvufOUIh8U25d": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/LyqqvufOUIh8U25d",
        "id"          : "LyqqvufOUIh8U25d",
        "price"       : null,
        "required"    : [],
        "text"        : "Extension de magie du sang",
        "traits"      : []
    },
    "acJkVtpX2GUvl90E": {
        "action_cost" : "1",
        "bulk"        : null,
        "category"    : "feat",
        "description" : "<p>Vous posez un doigt sur la balance de la vie et de la mort pour soigner une créature, qu'elle soit vivante ou morte-vivante. Vous rendez  2 + le double de votre niveau de Points de vie  à une créature dans les 9 mètres.</p>\n<p>En outre, vous pouvez servir de médiateur au cours de vos préparatifs quotidiens et vous placer d'un des deux côtés de la balance. Choisissez la vie ou la mort. Si vous vous alignez sur la vie, vous êtes soigné par les effets de guérison de vitalité, comme c'est le cas pour la plupart des créatures vivantes. Si vous vous alignez sur la mort, vous obtenez la capacité guérison du vide, qui vous permet d'être soigné par les effets du vide qui restaurent des Points de vie et tous les autres effets qui redonnent des Points de vie aux créatures mortes-vivantes.</p>",
        "element_type": "DON 1",
        "href"        : "/feats/acJkVtpX2GUvl90E",
        "id"          : "acJkVtpX2GUvl90E",
        "price"       : null,
        "required"    : [],
        "text"        : "Faire pencher la balance",
        "traits"      : [
            "Lié à une malédiction",
            "Divin",
            "Guérison",
            "Oracle",
            "Spirituel"
        ]
    },
    "VaIHQzOE5ibmbtqU": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/VaIHQzOE5ibmbtqU",
        "id"          : "VaIHQzOE5ibmbtqU",
        "price"       : null,
        "required"    : [],
        "text"        : "Forme indomptée",
        "traits"      : []
    },
    "RQH6vigvhmiYKKjg": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/RQH6vigvhmiYKKjg",
        "id"          : "RQH6vigvhmiYKKjg",
        "price"       : null,
        "required"    : [],
        "text"        : "Frappe précise",
        "traits"      : []
    },
    "EAP98XaChJEbgKcK": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/EAP98XaChJEbgKcK",
        "id"          : "EAP98XaChJEbgKcK",
        "price"       : null,
        "required"    : [],
        "text"        : "Frappe punitive",
        "traits"      : []
    },
    "sGenGMmE1ntkXCtN": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/sGenGMmE1ntkXCtN",
        "id"          : "sGenGMmE1ntkXCtN",
        "price"       : null,
        "required"    : [],
        "text"        : "Incantation Interdisciplinaire",
        "traits"      : []
    },
    "zJxUflt9np0q4yML": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "condition",
        "description" : "<p>Vous ne pouvez pas être vu. Vous êtes  <div class=\"gs-link-information\" onclick=\"CONTROLLER.Main.doActionAfter('event__show_information', {'param__object__uuid': 'VRSef5y1LmL2Hkjf'})\">Non détecté</div>  par quiconque. Les créatures peuvent  <div class=\"gs-link-information\" onclick=\"CONTROLLER.Main.doActionAfter('event__show_information', {'param__object__uuid': 'BlAOM2X92SI6HMtJ'})\">Chercher</div>  pour vous détecter. Si une créature réussit son test de Perception opposé à votre DD de Discrétion, vous êtes  <div class=\"gs-link-information\" onclick=\"CONTROLLER.Main.doActionAfter('event__show_information', {'param__object__uuid': 'iU0fEDdBp3rXpTMC'})\">Caché</div>  à l'égard de cette créature jusqu'à ce que vous réussissiez à  <div class=\"gs-link-information\" onclick=\"CONTROLLER.Main.doActionAfter('event__show_information', {'param__object__uuid': 'VMozDqMMuK5kpoX4'})\">Être furtif</div>  pour devenir Non détecté de nouveau. Si vous devenez invisible alors que quelqu'un peut déjà vous voir, vous commencez dans l'état Caché à son égard (au lieu de Non détecté) jusqu'à ce que vous réussissiez à Être furtif. Vous ne pouvez pas devenir  <div class=\"gs-link-information\" onclick=\"CONTROLLER.Main.doActionAfter('event__show_information', {'param__object__uuid': '1wQY3JYyhMYeeV2G'})\">Observé</div>  alors que vous êtes invisible, sauf par le biais de capacités spéciales ou la magie.</p>",
        "element_type": null,
        "href"        : "/conditions/zJxUflt9np0q4yML",
        "id"          : "zJxUflt9np0q4yML",
        "price"       : null,
        "required"    : [],
        "text"        : "Invisible",
        "traits"      : []
    },
    "au0lwQ1nAcNQwcGh": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/au0lwQ1nAcNQwcGh",
        "id"          : "au0lwQ1nAcNQwcGh",
        "price"       : null,
        "required"    : [],
        "text"        : "Lien arcanique",
        "traits"      : []
    },
    "Dy1cyGJUfzyZ4EIy": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/Dy1cyGJUfzyZ4EIy",
        "id"          : "Dy1cyGJUfzyZ4EIy",
        "price"       : null,
        "required"    : [],
        "text"        : "Lignages d'ensorceleur draconique",
        "traits"      : []
    },
    "tuZnRWHixLArvaIf": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/tuZnRWHixLArvaIf",
        "id"          : "tuZnRWHixLArvaIf",
        "price"       : null,
        "required"    : [],
        "text"        : "Lueur de rédemption",
        "traits"      : []
    },
    "PRrZ7anETWPm90YY": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/PRrZ7anETWPm90YY",
        "id"          : "PRrZ7anETWPm90YY",
        "price"       : null,
        "required"    : [],
        "text"        : "Magie déguisée",
        "traits"      : []
    },
    "kUSShxXzY1sPtJA0": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/kUSShxXzY1sPtJA0",
        "id"          : "kUSShxXzY1sPtJA0",
        "price"       : null,
        "required"    : [],
        "text"        : "Magie détonante",
        "traits"      : []
    },
    "XQjR07LkDedC7tkc": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/XQjR07LkDedC7tkc",
        "id"          : "XQjR07LkDedC7tkc",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction de l'afflux de connaissances",
        "traits"      : []
    },
    "d03gBFLK4XJlDNNh": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/d03gBFLK4XJlDNNh",
        "id"          : "d03gBFLK4XJlDNNh",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction de l'appel des cieux",
        "traits"      : []
    },
    "vXnMKFIxqLuCDW9q": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/vXnMKFIxqLuCDW9q",
        "id"          : "vXnMKFIxqLuCDW9q",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction de l'incursion ancestrale",
        "traits"      : []
    },
    "8ODGE24gqEdzWljj": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/8ODGE24gqEdzWljj",
        "id"          : "8ODGE24gqEdzWljj",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction de la mort vivante",
        "traits"      : []
    },
    "5QVUaQGT1FSkFOYP": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/5QVUaQGT1FSkFOYP",
        "id"          : "5QVUaQGT1FSkFOYP",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction de la pourriture inévitable",
        "traits"      : []
    },
    "zO7dvBgLuhdGfP5t": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/zO7dvBgLuhdGfP5t",
        "id"          : "zO7dvBgLuhdGfP5t",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction de la vie déversée",
        "traits"      : []
    },
    "2VclK5CWR1Vz1vqL": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/2VclK5CWR1Vz1vqL",
        "id"          : "2VclK5CWR1Vz1vqL",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction des cendres rampantes",
        "traits"      : []
    },
    "RI2UHuUZd3TC1OE8": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/RI2UHuUZd3TC1OE8",
        "id"          : "RI2UHuUZd3TC1OE8",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction des flammes engloutissantes",
        "traits"      : []
    },
    "X6GQ4ngqpjP8SpCq": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/X6GQ4ngqpjP8SpCq",
        "id"          : "X6GQ4ngqpjP8SpCq",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction des moments de turbulence",
        "traits"      : []
    },
    "LIV2gH3ZUFlu0zu4": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/LIV2gH3ZUFlu0zu4",
        "id"          : "LIV2gH3ZUFlu0zu4",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction des vents contraires",
        "traits"      : []
    },
    "zLYqrQdheciiW2nm": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/zLYqrQdheciiW2nm",
        "id"          : "zLYqrQdheciiW2nm",
        "price"       : null,
        "required"    : [],
        "text"        : "Malédiction du combattant mortel",
        "traits"      : []
    },
    "55WR55op9BIdgF1B": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/55WR55op9BIdgF1B",
        "id"          : "55WR55op9BIdgF1B",
        "price"       : null,
        "required"    : [],
        "text"        : "Murmures de faiblesse",
        "traits"      : []
    },
    "wYerMk6F1RZb0Fwt": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/wYerMk6F1RZb0Fwt",
        "id"          : "wYerMk6F1RZb0Fwt",
        "price"       : null,
        "required"    : [],
        "text"        : "Médecine militaire",
        "traits"      : []
    },
    "YNAthsgsJjQIXbc8": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/YNAthsgsJjQIXbc8",
        "id"          : "YNAthsgsJjQIXbc8",
        "price"       : null,
        "required"    : [],
        "text"        : "Négociateur de pacte",
        "traits"      : []
    },
    "M8RCbthRhB4bxO9t": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/M8RCbthRhB4bxO9t",
        "id"          : "M8RCbthRhB4bxO9t",
        "price"       : null,
        "required"    : [],
        "text"        : "Ordre de fer",
        "traits"      : []
    },
    "LzYi0OuOoypNb6jd": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/LzYi0OuOoypNb6jd",
        "id"          : "LzYi0OuOoypNb6jd",
        "price"       : null,
        "required"    : [],
        "text"        : "Panache",
        "traits"      : []
    },
    "6ON8DjFXSMITZleX": {
        "action_cost" : "3",
        "bulk"        : null,
        "category"    : "feat",
        "description" : "<p>Vous tentez de réduire la panique. Faites un test de  Diplomatie  et comparez le au DD de Volonté des créatures dans une  émanation de 3 mètres  autour de vous qui sont  <div class=\"gs-link-information\" onclick=\"CONTROLLER.Main.doActionAfter('event__show_information', {'param__object__uuid': 'TBSHQspnbcqxsmjL'})\">Effrayées</div> . Chacune d'entre elle est ensuite temporairement immunisée pendant 1 heure à l'utilisation de ce don.</p>\n<p>\"Succès critique\" Réduisez l'état Effrayé de la créature de 2.</p>\n<p>\"Succès\" Réduisez l'état Effrayé de la créature de 1.</p>",
        "element_type": "DON 1",
        "href"        : "/feats/6ON8DjFXSMITZleX",
        "id"          : "6ON8DjFXSMITZleX",
        "price"       : null,
        "required"    : [
            "qualifié en Diplomatie"
        ],
        "text"        : "Pas besoin de s'alarmer",
        "traits"      : [
            "Audible",
            "Concentration",
            "Émotion",
            "Général",
            "Linguistique",
            "Mental",
            "Compétence"
        ]
    },
    "kS4wxSKrZxcOvSNK": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/kS4wxSKrZxcOvSNK",
        "id"          : "kS4wxSKrZxcOvSNK",
        "price"       : null,
        "required"    : [],
        "text"        : "Pas du littoral",
        "traits"      : []
    },
    "aEM2cttJ2eYcLssW": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/aEM2cttJ2eYcLssW",
        "id"          : "aEM2cttJ2eYcLssW",
        "price"       : null,
        "required"    : [],
        "text"        : "Pas rapide",
        "traits"      : []
    },
    "QEOe9AhQzdqIx1ei": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/QEOe9AhQzdqIx1ei",
        "id"          : "QEOe9AhQzdqIx1ei",
        "price"       : null,
        "required"    : [],
        "text"        : "Pierre stable",
        "traits"      : []
    },
    "yOloZIGkulrrPYG4": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/yOloZIGkulrrPYG4",
        "id"          : "yOloZIGkulrrPYG4",
        "price"       : null,
        "required"    : [],
        "text"        : "Poumon de feu",
        "traits"      : []
    },
    "CuVvDrBaVP9nYJlt": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/CuVvDrBaVP9nYJlt",
        "id"          : "CuVvDrBaVP9nYJlt",
        "price"       : null,
        "required"    : [],
        "text"        : "Prédire le mal",
        "traits"      : []
    },
    "N91EI7H1p7YXKX0o": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/N91EI7H1p7YXKX0o",
        "id"          : "N91EI7H1p7YXKX0o",
        "price"       : null,
        "required"    : [],
        "text"        : "Puits runique personnel",
        "traits"      : []
    },
    "xccOiNL2W1EtfUYl": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/xccOiNL2W1EtfUYl",
        "id"          : "xccOiNL2W1EtfUYl",
        "price"       : null,
        "required"    : [],
        "text"        : "Question imparable",
        "traits"      : []
    },
    "plBGdZhqq5JBl1D8": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "<p>Vous sondez les marchés, les tavernes et les lieux de rassemblements locaux afin de tenter de recueillir des informations sur un individu ou un sujet particulier. Le MJ détermine le DD du test de  Diplomatie  et le temps que cela prend (typiquement 2 heures, mais parfois davantage), ainsi que de tout avantage dont vous pouvez bénéficier en dépensant de l'argent en pots-de-vin, en boissons ou en cadeaux.</p>\n<p>\"Succès\" Vous recueillez des informations sur l'individu ou le sujet. Le MJ en détermine le contenu.</p>\n<p>\"Échec critique\" Vous recueillez des informations erronées sur l'individu ou le sujet.</p>\nRecueillir des informations : exemples de tâches\n\n\"Inexpérimenté\" ce dont tout le monde parle en ville\n\"Qualifié\" rumeur connue\n\"Expert\" rumeur obscure, secret mal gardé\n\"Maître\" information ésotérique ou bien gardée\n\"Légendaire\" information connue par un nombre d'élus réduits ou seulement par des êtres extraordinaires",
        "element_type": null,
        "href"        : "/actions/plBGdZhqq5JBl1D8",
        "id"          : "plBGdZhqq5JBl1D8",
        "price"       : null,
        "required"    : [],
        "text"        : "Recueillir des informations",
        "traits"      : [
            "Exploration",
            "Secret"
        ]
    },
    "AmV13b9ncALtWJFt": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/AmV13b9ncALtWJFt",
        "id"          : "AmV13b9ncALtWJFt",
        "price"       : null,
        "required"    : [],
        "text"        : "Rediriger les éléments",
        "traits"      : []
    },
    "q1iP3SjAF5uceI0M": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/q1iP3SjAF5uceI0M",
        "id"          : "q1iP3SjAF5uceI0M",
        "price"       : null,
        "required"    : [],
        "text"        : "Représentation martiale",
        "traits"      : []
    },
    "6sNjsNPipZvQ3BGe": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/6sNjsNPipZvQ3BGe",
        "id"          : "6sNjsNPipZvQ3BGe",
        "price"       : null,
        "required"    : [],
        "text"        : "Retraite rapide",
        "traits"      : []
    },
    "gU7epgcPSm0TD1UK": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/gU7epgcPSm0TD1UK",
        "id"          : "gU7epgcPSm0TD1UK",
        "price"       : null,
        "required"    : [],
        "text"        : "Robes défensives",
        "traits"      : []
    },
    "XttSGDuAsRDTuvgS": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/XttSGDuAsRDTuvgS",
        "id"          : "XttSGDuAsRDTuvgS",
        "price"       : null,
        "required"    : [],
        "text"        : "Répercussions de fer",
        "traits"      : []
    },
    "Q7QQ91vQtyi1Ux36": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/Q7QQ91vQtyi1Ux36",
        "id"          : "Q7QQ91vQtyi1Ux36",
        "price"       : null,
        "required"    : [],
        "text"        : "Saut",
        "traits"      : []
    },
    "gxwmzxUWBOhdgFSN": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "deity",
        "description" : "<p>Connaître Shélyn, c'est l'aimer, car Shélyn incarne l'amour, ainsi que la beauté, l'art et la musique. Elle cherche à répandre ces pursuits à travers Golarion, enseignant qu'ils sont le meilleur moyen de trouver la paix et le bonheur. Sa passion est telle que même les tentatives les plus basiques en matière d'art la ravissent — les plus grandes sculptures de marbre de Taldor ou les chants kholo de l'étendue de Mwangi lui sont aussi chers que les croquis les plus simples d'un jeune orphelin d'Isger ou l'art de sable rudimentaire d'un enfant de Thuvia. Pour Shélyn, la beauté est une qualité de l'être, et non un ensemble spécifique de caractéristiques, et elle encourage les gens à trouver et à accepter de nombreuses définitions de celle-ci.</p>\n<p>\"Titre\" La Rose Éternelle</p>\n<p>\"Préoccupations\" art, beauté, amour, musique</p>\n<p>\"Édits\" Se montrer pacifique, choisir et perfectionner un art, guider par l'exemple, voir la beauté en toute chose.</p>\n<p>\"Anathèmes\" Détruire une œuvre d'art ou la laisser détruire à moins que ce ne soit pour sauver une vie ou accomplir une œuvre encore plus belle, refuser d'accepter une reddition.</p>\n<p>\"Symbole Religieux\" oiseau chanteur multicolore</p>\n<p>\"Animal sacré\" oiseau chanteur</p>\n<p>\"Couleurs sacrées\" toutes</p>",
        "element_type": null,
        "href"        : "/deities/gxwmzxUWBOhdgFSN",
        "id"          : "gxwmzxUWBOhdgFSN",
        "price"       : null,
        "required"    : [],
        "text"        : "Shélyn",
        "traits"      : []
    },
    "M89l9FOnjHe63wD7": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/M89l9FOnjHe63wD7",
        "id"          : "M89l9FOnjHe63wD7",
        "price"       : null,
        "required"    : [],
        "text"        : "Thèse arcanique",
        "traits"      : []
    },
    "UtINSoEJ0u630ia4": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "action",
        "description" : "",
        "element_type": null,
        "href"        : "/actions/UtINSoEJ0u630ia4",
        "id"          : "UtINSoEJ0u630ia4",
        "price"       : null,
        "required"    : [],
        "text"        : "Tirer hors de danger",
        "traits"      : []
    },
    "mxO7u59ms58q7zyj": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/mxO7u59ms58q7zyj",
        "id"          : "mxO7u59ms58q7zyj",
        "price"       : null,
        "required"    : [],
        "text"        : "Trompeur magique",
        "traits"      : []
    },
    "r5Uth6yvCoE4tr9z": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "spell",
        "description" : "",
        "element_type": null,
        "href"        : "/spells/r5Uth6yvCoE4tr9z",
        "id"          : "r5Uth6yvCoE4tr9z",
        "price"       : null,
        "required"    : [],
        "text"        : "Vengeance destructrice",
        "traits"      : []
    },
    "1HfusQ8NDWutGvMx": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/1HfusQ8NDWutGvMx",
        "id"          : "1HfusQ8NDWutGvMx",
        "price"       : null,
        "required"    : [],
        "text"        : "Vision animale",
        "traits"      : []
    },
    "DUOb8QrlC5t0adkL": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "feat",
        "description" : "",
        "element_type": null,
        "href"        : "/feats/DUOb8QrlC5t0adkL",
        "id"          : "DUOb8QrlC5t0adkL",
        "price"       : null,
        "required"    : [],
        "text"        : "Vitesse de voyage",
        "traits"      : []
    },
    "RDXXE7wMrSPCLv5k": {
        "action_cost" : "1",
        "bulk"        : null,
        "category"    : "action",
        "description" : "<p>Vous tentez de vous emparer d'un objet en possession d'une autre créature sans vous faire repérer. Généralement, vous ne pouvez Voler qu'un objet dont l'Encombrement est négligeable, vous devez disposer d'une main libre et vous obtenez automatiquement un échec si la créature qui porte l'objet est en combat ou sur ses gardes.</p>\n<p>Faites un test de  Vol  pour déterminer si vous réussissez à Voler l'objet. Le DD est habituellement le DD de Perception de la créature qui porte l'objet. Il est plus facile de voler un objet qui est porté mais qui n'est pas surveillé de près (comme une bourse pleine de pièces portée en évidence à la ceinture ou un objet dans une telle bourse). Le MJ pourrait augmenter le DD si l'objet est protégé ou si la nature de l'objet le rend plus difficile à voler (comme un très petit objet dans un grand sac ou une feuille de parchemin mélangée à d'autres documents). Par exemple, le DD serait de 5 supérieur si l'objet se trouve dans une poche, tenu en main par la créature ou protégée de manière similaire.</p>\n<p>Vous pourriez également avoir besoin de comparer le résultat de votre test de Vol aux DD de Perception des observateurs autres que la personne qui porte l'objet. Le MJ pourrait imposer une pénalité de circonstances aux spectateurs qui sont distraits.</p>\n<p>\"Succès\" Vous volez l'objet sans que son détenteur ne le remarque ou l'observateur ne vous voit pas prendre ou tenter de prendre l'objet.</p>\n<p>\"Échec\" Le détenteur de l'objet remarque votre tentative avant que vous ne puissiez prendre l'objet ou l'observateur vous voit prendre ou tenter de prendre l'objet. Le MJ détermine la réaction de chaque créature qui remarquent votre vol.</p>",
        "element_type": null,
        "href"        : "/actions/RDXXE7wMrSPCLv5k",
        "id"          : "RDXXE7wMrSPCLv5k",
        "price"       : null,
        "required"    : [],
        "text"        : "Voler",
        "traits"      : [
            "Manipulation"
        ]
    },
    "PVXqMko4yGgw90uo": {
        "action_cost" : "2",
        "bulk"        : null,
        "category"    : "spell",
        "description" : "<p>Vous entourez votre cible d'illusions merveilleuses de ses plus grands désirs, ce qui la distrait de la réalité. La cible doit tenter un jet de Volonté.</p>\n<p>\"Succès critique\" La cible perce l'illusion et n'est pas affectée.</p>\n<p>\"Succès\" Pendant 1 round, la cible est  <div class=\"gs-link-information\" onclick=\"CONTROLLER.Main.doActionAfter('event__show_information', {'param__object__uuid': 'e1XGnhKNSQIm5IXg'})\">Stupéfiée 2</div>  et subit une pénalité de statut de -2 à tout test qu'elle réalise pour déterminer les effets des réactions.</p>\n<p>\"Échec\" Pendant 1 minute, la cible est Stupéfiée 2 et ne peut utiliser de réaction.</p>\n<p>\"Échec critique\" Comme en cas d'échec et toutes les cases sont un terrain difficile pour la cible.</p>\n<p>\"Intensifié (+2)\" Vous pouvez cibler une créature supplémentaire.</p>",
        "element_type": "FOCALISÉ 3",
        "href"        : "/spells/PVXqMko4yGgw90uo",
        "id"          : "PVXqMko4yGgw90uo",
        "price"       : null,
        "required"    : [],
        "text"        : "désir du cœur",
        "traits"      : [
            "Peu courant",
            "Concentration",
            "Émotion",
            "Focalisation",
            "Illusion",
            "Manipulation",
            "Mental",
            "Ensorceleur"
        ]
    },
    "PBQh0amk1FlomV0r": {
        "action_cost" : null,
        "bulk"        : null,
        "category"    : "item",
        "description" : "",
        "element_type": null,
        "href"        : "/equipment/PBQh0amk1FlomV0r",
        "id"          : "PBQh0amk1FlomV0r",
        "price"       : null,
        "required"    : [],
        "text"        : "fioles polyvalentes",
        "traits"      : []
    },
    "ITWUi1r8Z7EtChkB": {
        "category"    : "spell",
        "href"        : "/spells/ITWUi1r8Z7EtChkB",
        "id"          : "ITWUi1r8Z7EtChkB",
        "text"        : "Éclair de grandeur",
        "element_type": null,
        "action_cost" : null,
        "traits"      : [],
        "required"    : [],
        "price"       : null,
        "bulk"        : null,
        "description" : ""
    }
};